#!/bin/bash
set -xeu

pwd
printenv

# setup data directory
mkdir -p $SNAP_DATA/storage
chmod -R 750 $SNAP_DATA/storage
cp -rf $SNAP/var/www/html/multi-chat/storage $SNAP_DATA/
mount -o rw --bind $SNAP_DATA/storage $SNAP/var/www/html/multi-chat/storage

cd $SNAP/var/www/html/multi-chat
php -m

php artisan migrate --force
php artisan db:seed --class=AdminSeeder --force

$SNAP/etc/init.d/nginx restart