.venv
/vendor/
node_modules/
npm-debug.log
yarn-error.log

# Laravel 5 & Lumen specific
public/storage
public/hot
public/build

# Laravel 5 & Lumen specific with changed public path
public_html/storage
public_html/hot

storage/*.key
.env
.env.backup
.env.production
Homestead.yaml
Homestead.json
/.vagrant
.phpunit.cache
.phpunit.result.cache

# Data
exported_data.json
converted_data.jsonl
*.sqlite
*auth.json
demo