#!/bin/bash
set -e

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--num-worker)
      NUM_WORKER=$2
      shift # past argument
      shift # past value
      ;;
    -h|--help)
      echo "Usage: $0 [-n|--num-worker] [--help]"
      echo "Options:"
      echo "  -n, --num-worker: Number of workers"
      echo "  -h, --help: Print this usage information"
      exit 0
      ;;
    *)
      echo "Invalid argument: $1"
      exit 1
      ;;
  esac
done

NUM_WORKER=${NUM_WORKER:-1}
echo "Number of redis workers: $NUM_WORKER"
php artisan worker:start "$NUM_WORKER"
exec php-fpm