# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\"\'\n\x14MessageFilterRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\x0fQaFilterRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"@\n\x10\x43heckingResponse\x12\x0c\n\x04safe\x18\x01 \x01(\x08\x12\x13\n\x06\x64\x65tail\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_detail2{\n\tDetection\x12;\n\rMessageFilter\x12\x15.MessageFilterRequest\x1a\x11.CheckingResponse\"\x00\x12\x31\n\x08QaFilter\x12\x10.QaFilterRequest\x1a\x11.CheckingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEFILTERREQUEST']._serialized_start=19
  _globals['_MESSAGEFILTERREQUEST']._serialized_end=58
  _globals['_QAFILTERREQUEST']._serialized_start=60
  _globals['_QAFILTERREQUEST']._serialized_end=111
  _globals['_CHECKINGRESPONSE']._serialized_start=113
  _globals['_CHECKINGRESPONSE']._serialized_end=177
  _globals['_DETECTION']._serialized_start=179
  _globals['_DETECTION']._serialized_end=302
# @@protoc_insertion_point(module_scope)
