# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detection_pb2 as detection__pb2


class DetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MessageFilter = channel.unary_unary(
                '/Detection/MessageFilter',
                request_serializer=detection__pb2.MessageFilterRequest.SerializeToString,
                response_deserializer=detection__pb2.CheckingResponse.FromString,
                )
        self.QaFilter = channel.unary_unary(
                '/Detection/QaFilter',
                request_serializer=detection__pb2.QaFilterRequest.SerializeToString,
                response_deserializer=detection__pb2.CheckingResponse.FromString,
                )


class DetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MessageFilter(self, request, context):
        """Perform the safety check on a single message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QaFilter(self, request, context):
        """Perform the safety check on a prompt-response pair.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MessageFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.MessageFilter,
                    request_deserializer=detection__pb2.MessageFilterRequest.FromString,
                    response_serializer=detection__pb2.CheckingResponse.SerializeToString,
            ),
            'QaFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.QaFilter,
                    request_deserializer=detection__pb2.QaFilterRequest.FromString,
                    response_serializer=detection__pb2.CheckingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Detection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Detection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MessageFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Detection/MessageFilter',
            detection__pb2.MessageFilterRequest.SerializeToString,
            detection__pb2.CheckingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QaFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Detection/QaFilter',
            detection__pb2.QaFilterRequest.SerializeToString,
            detection__pb2.CheckingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
