# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detection_pb2 as detection__pb2


class DetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreFilter = channel.unary_unary(
                '/Detection/PreFilter',
                request_serializer=detection__pb2.FilterRequest.SerializeToString,
                response_deserializer=detection__pb2.CheckingResponse.FromString,
                )
        self.PostFilter = channel.unary_unary(
                '/Detection/PostFilter',
                request_serializer=detection__pb2.FilterRequest.SerializeToString,
                response_deserializer=detection__pb2.CheckingResponse.FromString,
                )


class DetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PreFilter(self, request, context):
        """Check whether the user input is safe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostFilter(self, request, context):
        """Check whether the model output is safe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.PreFilter,
                    request_deserializer=detection__pb2.FilterRequest.FromString,
                    response_serializer=detection__pb2.CheckingResponse.SerializeToString,
            ),
            'PostFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.PostFilter,
                    request_deserializer=detection__pb2.FilterRequest.FromString,
                    response_serializer=detection__pb2.CheckingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Detection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Detection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PreFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Detection/PreFilter',
            detection__pb2.FilterRequest.SerializeToString,
            detection__pb2.CheckingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Detection/PostFilter',
            detection__pb2.FilterRequest.SerializeToString,
            detection__pb2.CheckingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
