services:
  custom-dbqa-executor:
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./docqa/docqa.py
      EXECUTOR_ACCESS_CODE: db-qa:custom-db
      EXECUTOR_NAME: DB QA (Custom DB)
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    volumes: [
      "</path/to/vector-database>:/var/database/",
      "kuwa-root:/var/kuwa/docker/root:rw", # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
      "~/.cache/huggingface:/root/.cache/huggingface"
    ]
    depends_on:
      - kernel
      - multi-chat
    command: [
      "--api_base_url", "http://web/",
      "--model", "gemini-pro",
      "--database", "/var/database/",
      "--log", "debug"
      ]
    restart: unless-stopped
    networks: ["backend", "frontend"]