services:
  token-counter-executor:
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./expert/main.py
      EXECUTOR_ACCESS_CODE: tool/expert
      EXECUTOR_NAME: Expert Bot
      EXECUTOR_IMAGE: TAIDE.png # Refer to src/multi-chat/public/images
    depends_on:
      - kernel
      - multi-chat
    command: []
    restart: unless-stopped
    networks: ["backend"]