version: '3'

services:
  web_agent:
    image: taide_web_agent
    build: .
    environment:
      TZ: 'Asia/Taipei'
      WEBROOT: '/var/www/html/TAIDE/public'
      PHP_APP_PATH: /var/www/html/TAIDE
      PHP_REDIS_SESSION_HOST: 'redis'
      CREATE_LARAVEL_STORAGE: '1'
      COMPOSERMIRROR: 'https://mirrors.cloud.tencent.com/composer/'
      NPMMIRROR: 'https://registry.npmmirror.com'
    ports:
      - "8080:80"
    volumes:
      - ../../web:/var/www/html/TAIDE
      - ../../LLMs/agent:/agent
    networks:
      - backend
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/debug"]
      interval: 15s
      timeout: 5s
      retries: 10

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: LLMProject
      POSTGRES_USER: llmprojectroot
      POSTGRES_DB: llm_project
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U llmprojectroot -d llm_project -t 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
